### ISSUE TITLE
implement rest of descriptors

### ISSUE THREAD

**Issue by xMOROx** [xMOROx/netpix#73]
## TODO
- [ ] Smoothing buffer descriptor
- [ ] IBP descriptor
- [ ] MPEG-4 video descriptor
- [ ] MPEG-4 audio descriptor
- [ ] Content labelling descriptor
- [ ] Metadata pointer descriptor
- [ ] Metadata descriptor
- [ ] Metadata STD descriptor
- [ ] MPEG-2 AAC audio descriptor
- [ ] MPEG2 stereoscopic video format descriptor
- [ ] Stereoscopic program info descriptor
- [ ] Stereoscopic video info descriptor
- [ ] Transport profile descriptor
