### ISSUE TITLE
server-side packets discharger

### ISSUE THREAD

**Issue by xMOROx** [xMOROx/netpix#76]
## TODO 
- [x] Server-side discharging packets after some time and/or after ringbuf limit reached
- [ ] Apply limit rate to sending messages from server to client

## DONE 
- [x] Change `ethernet` to `pnet` -> better performance and availability to clone/copy
- [x] Refactor server code
